'use client'

import { useMemo, useState } from 'react'

function Artwork({ sermon, priority = false }) {
  return <div className="relative h-full w-full overflow-hidden bg-gradient-to-br from-midnight-navy via-[#17385d] to-[#315d89]">
    {sermon.image ? <img src={sermon.image} alt="" loading={priority ? 'eager' : 'lazy'} className="absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.025]" /> : <span className="absolute inset-0 grid place-items-center"><span className="material-symbols-outlined text-7xl text-white/60">graphic_eq</span></span>}
    <div className="absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-black/5" />
  </div>
}

export default function SermonsPage({ sermons = [] }) {
  const [query, setQuery] = useState('')
  const [series, setSeries] = useState('All series')
  const [speaker, setSpeaker] = useState('All speakers')
  const seriesOptions = [...new Set(sermons.map((item) => item.series).filter(Boolean))].sort()
  const speakerOptions = [...new Set(sermons.map((item) => item.speaker).filter(Boolean))].sort()
  const visible = useMemo(() => {
    const term = query.trim().toLowerCase()
    return sermons.filter((item) => (!term || [item.title, item.speaker, item.scripture, item.series, item.description].some((value) => value?.toLowerCase().includes(term))) && (series === 'All series' || item.series === series) && (speaker === 'All speakers' || item.speaker === speaker))
  }, [query, series, sermons, speaker])
  const featured = visible[0]
  const rest = visible.slice(1)

  return <>
    <header className="relative overflow-hidden bg-midnight-navy pb-20 pt-36 text-white md:pb-24 md:pt-44"><div className="absolute inset-0 opacity-20 [background-image:radial-gradient(circle_at_80%_15%,#c5a059_0,transparent_25%),radial-gradient(circle_at_15%_90%,#315d89_0,transparent_30%)]" /><div className="page-shell relative"><p className="flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.22em] text-heritage-gold"><span className="h-px w-8 bg-heritage-gold" />Preaching and teaching</p><div className="mt-6 grid gap-8 lg:grid-cols-[1fr_0.65fr] lg:items-end"><h1 className="font-display text-6xl leading-[0.9] tracking-[-0.035em] md:text-8xl">Hear the Word<br /><em className="font-normal text-white/55">faithfully preached.</em></h1><p className="max-w-xl border-l border-white/15 pl-6 text-base leading-7 text-white/60">Biblical preaching for the church in Africa and beyond. Listen, watch, study Scripture, and explore messages by speaker and series.</p></div></div></header>
    <main className="bg-[#f5f3ee] py-10 md:py-16"><div className="page-shell">
      <section className="relative z-10 -mt-20 grid gap-3 rounded-2xl border border-midnight-navy/10 bg-white p-3 shadow-[0_18px_50px_rgba(13,34,64,0.11)] md:grid-cols-[1fr_220px_220px]" aria-label="Filter sermons"><label className="relative"><span className="material-symbols-outlined absolute left-4 top-1/2 -translate-y-1/2 text-midnight-navy/35">search</span><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full rounded-xl bg-[#f5f5f7] py-3.5 pl-12 pr-4 font-sans text-sm text-midnight-navy outline-none ring-midnight-navy/10 focus:ring-2" placeholder="Search sermons or Scripture" /></label><select value={series} onChange={(event) => setSeries(event.target.value)} className="rounded-xl border-0 bg-[#f5f5f7] px-4 py-3.5 font-sans text-sm text-midnight-navy outline-none"><option>All series</option>{seriesOptions.map((item) => <option key={item}>{item}</option>)}</select><select value={speaker} onChange={(event) => setSpeaker(event.target.value)} className="rounded-xl border-0 bg-[#f5f5f7] px-4 py-3.5 font-sans text-sm text-midnight-navy outline-none"><option>All speakers</option>{speakerOptions.map((item) => <option key={item}>{item}</option>)}</select></section>
      {featured ? <>
        <section className="mt-12"><div className="mb-5 flex items-center justify-between"><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-midnight-navy/45">Featured message</p><span className="font-sans text-xs text-midnight-navy/40">{visible.length} sermon{visible.length === 1 ? '' : 's'}</span></div><a href={`/sermons/${featured.slug}`} className="group grid overflow-hidden rounded-[28px] bg-white shadow-[0_20px_55px_rgba(13,34,64,0.10)] lg:grid-cols-[1.15fr_0.85fr]"><div className="aspect-[4/3] lg:aspect-auto lg:min-h-[490px]"><Artwork sermon={featured} priority /></div><div className="flex flex-col p-7 md:p-11"><div className="flex items-center justify-between"><span className="rounded-full bg-heritage-gold/10 px-3 py-1.5 text-[9px] font-bold uppercase tracking-[0.13em] text-[#9a7434]">{featured.series || 'TGN Sermon'}</span><span className="grid size-11 place-items-center rounded-full bg-midnight-navy text-white shadow-lg"><span className="material-symbols-outlined text-[21px]">{featured.videoUrl ? 'play_arrow' : 'headphones'}</span></span></div><h2 className="mt-8 font-display text-4xl leading-[1.03] tracking-[-0.025em] text-midnight-navy md:text-6xl">{featured.title}</h2><p className="mt-5 text-sm font-semibold text-midnight-navy">{featured.speaker}</p><p className="mt-2 font-sans text-xs text-midnight-navy/50">{featured.scripture || 'Scripture not listed'} <span className="mx-2">·</span> {featured.date}</p>{featured.description && <p className="mt-7 line-clamp-4 text-[15px] leading-7 text-midnight-navy/60">{featured.description}</p>}<span className="mt-auto inline-flex items-center gap-3 pt-9 font-sans text-[10px] font-bold uppercase tracking-[0.15em] text-midnight-navy">{featured.videoUrl ? 'Watch message' : 'Listen to message'}<span className="transition-transform group-hover:translate-x-1">→</span></span></div></a></section>
        <section className="mt-16"><div className="flex items-end justify-between border-b border-midnight-navy/15 pb-5"><div><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-heritage-gold">The archive</p><h2 className="mt-2 font-display text-4xl tracking-[-0.02em] text-midnight-navy md:text-5xl">Recent sermons</h2></div></div><div className="mt-7 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{rest.map((sermon) => <a key={sermon.id} href={`/sermons/${sermon.slug}`} className="group flex min-h-[430px] flex-col overflow-hidden rounded-[22px] border border-midnight-navy/[0.08] bg-white shadow-[0_8px_28px_rgba(13,34,64,0.055)] transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_18px_42px_rgba(13,34,64,0.12)]"><div className="relative aspect-[4/3] w-full shrink-0"><Artwork sermon={sermon} /><span className="absolute bottom-4 left-4 grid size-11 place-items-center rounded-full bg-white text-midnight-navy shadow-lg"><span className="material-symbols-outlined text-[20px]">{sermon.videoUrl ? 'play_arrow' : 'headphones'}</span></span></div><div className="flex grow flex-col p-6"><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-heritage-gold">{sermon.series || 'TGN Sermon'}</p><h3 className="mt-4 font-display text-[1.7rem] leading-[1.08] tracking-[-0.018em] text-midnight-navy">{sermon.title}</h3><p className="mt-4 text-xs font-semibold text-midnight-navy/70">{sermon.speaker}</p><div className="mt-auto flex items-end justify-between gap-4 border-t border-midnight-navy/[0.08] pt-5 font-sans text-[10px] leading-4 text-midnight-navy/45"><span>{sermon.scripture || 'Scripture not listed'}</span><span className="shrink-0">{sermon.date}</span></div></div></a>)}</div></section>
      </> : <div className="py-24 text-center"><span className="material-symbols-outlined text-5xl text-midnight-navy/20">podcasts</span><h2 className="mt-4 font-display text-3xl text-midnight-navy">No sermons found</h2><p className="mt-2 font-sans text-sm text-midnight-navy/45">Try changing your search or filters.</p></div>}
    </div></main>
  </>
}
