'use client'

import { useMemo, useState } from 'react'

export default function SermonsPage({ sermons = [] }) {
  const [query, setQuery] = useState('')
  const [series, setSeries] = useState('All series')
  const [speaker, setSpeaker] = useState('All speakers')
  const seriesOptions = [...new Set(sermons.map((item) => item.series).filter(Boolean))].sort()
  const speakerOptions = [...new Set(sermons.map((item) => item.speaker).filter(Boolean))].sort()
  const visible = useMemo(() => {
    const term = query.trim().toLowerCase()
    return sermons.filter((item) => (!term || [item.title, item.speaker, item.scripture, item.series, item.description].some((value) => value?.toLowerCase().includes(term))) && (series === 'All series' || item.series === series) && (speaker === 'All speakers' || item.speaker === speaker))
  }, [query, series, sermons, speaker])
  const featured = visible[0]
  const rest = visible.slice(1)
  return <>
    <header className="bg-midnight-navy pb-16 pt-36 text-white md:pb-20 md:pt-44"><div className="page-shell"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-heritage-gold">Preaching and teaching</p><div className="mt-5 grid gap-8 lg:grid-cols-[1fr_0.65fr] lg:items-end"><h1 className="font-display text-6xl leading-none md:text-8xl">Sermons</h1><p className="max-w-xl text-base leading-7 text-white/60">Listen to faithful biblical preaching for the church in Africa and beyond. Explore messages by Scripture, speaker, and sermon series.</p></div></div></header>
    <main className="bg-parchment-ivory py-12 md:py-16"><div className="page-shell"><section className="grid gap-3 border-y border-midnight-navy/15 py-5 md:grid-cols-[1fr_220px_220px]"><label className="relative"><span className="material-symbols-outlined absolute left-4 top-1/2 -translate-y-1/2 text-midnight-navy/35">search</span><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full border border-midnight-navy/15 bg-white py-3 pl-12 pr-4 text-sm outline-none" placeholder="Search sermons or Scripture…" /></label><select value={series} onChange={(event) => setSeries(event.target.value)} className="border border-midnight-navy/15 bg-white px-4 py-3 text-sm text-midnight-navy"><option>All series</option>{seriesOptions.map((item) => <option key={item}>{item}</option>)}</select><select value={speaker} onChange={(event) => setSpeaker(event.target.value)} className="border border-midnight-navy/15 bg-white px-4 py-3 text-sm text-midnight-navy"><option>All speakers</option>{speakerOptions.map((item) => <option key={item}>{item}</option>)}</select></section>
      {featured ? <><a href={`/sermons/${featured.slug}`} className="group mt-10 grid overflow-hidden bg-white shadow-sm lg:grid-cols-[1.25fr_0.75fr]"><div className="relative overflow-hidden"><img src={featured.image} alt="" className="aspect-[16/10] h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.02]" /><span className="absolute left-5 top-5 bg-midnight-navy px-3 py-1.5 text-[9px] font-bold uppercase tracking-[0.12em] text-white">Latest sermon</span></div><div className="flex flex-col p-7 md:p-10"><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-heritage-gold">{featured.series || 'TGN Sermons'}</p><h2 className="mt-5 font-display text-4xl leading-tight text-midnight-navy md:text-5xl">{featured.title}</h2><p className="mt-4 text-sm font-semibold text-midnight-navy/70">{featured.speaker}</p><p className="mt-1 text-xs text-midnight-navy/45">{featured.scripture} · {featured.date}</p><p className="mt-6 line-clamp-4 text-sm leading-7 text-midnight-navy/60">{featured.description}</p><span className="mt-auto pt-8 text-[11px] font-bold uppercase tracking-[0.13em] text-midnight-navy">{featured.mediaType === 'video' ? 'Watch sermon' : 'Listen to sermon'} →</span></div></a>
        <section className="mt-14"><div className="flex items-end justify-between border-b border-midnight-navy/15 pb-4"><div><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-heritage-gold">Archive</p><h2 className="mt-2 font-display text-4xl text-midnight-navy">Recent sermons</h2></div><span className="text-xs text-midnight-navy/40">{visible.length} message{visible.length === 1 ? '' : 's'}</span></div><div className="grid gap-px bg-midnight-navy/10 sm:grid-cols-2 lg:grid-cols-3">{rest.map((sermon) => <a key={sermon.id} href={`/sermons/${sermon.slug}`} className="group flex min-h-[410px] flex-col bg-white"><div className="relative overflow-hidden"><img src={sermon.image} alt="" className="aspect-[16/9] w-full object-cover transition-transform duration-500 group-hover:scale-[1.025]" /><span className="absolute bottom-3 left-3 grid size-10 place-items-center rounded-full bg-white text-midnight-navy shadow"><span className="material-symbols-outlined text-[19px]">{sermon.mediaType === 'video' ? 'play_arrow' : 'headphones'}</span></span></div><div className="flex grow flex-col p-5"><p className="text-[9px] font-bold uppercase tracking-[0.13em] text-heritage-gold">{sermon.series || 'Sermon'}</p><h3 className="mt-3 font-display text-2xl leading-tight text-midnight-navy">{sermon.title}</h3><p className="mt-3 text-xs font-semibold text-midnight-navy/65">{sermon.speaker}</p><p className="mt-auto pt-6 text-[11px] text-midnight-navy/40">{sermon.scripture || 'Scripture not listed'} · {sermon.date}</p></div></a>)}</div></section></> : <div className="py-24 text-center"><span className="material-symbols-outlined text-4xl text-midnight-navy/25">podcasts</span><h2 className="mt-4 font-display text-3xl text-midnight-navy">No sermons found</h2><p className="mt-2 text-sm text-midnight-navy/45">Try changing your search or filters.</p></div>}
    </div></main>
  </>
}
